"""Reviewed Level-3 pages that do not require a shader walkthrough.

Populate this mapping only after the page has been source-backed reviewed. Keys are
category directory names and values are sets of Markdown filenames.
"""

PAGES_WITHOUT_WALKTHROUGH: dict[str, set[str]] = {
    'api': {
        'Blitting.md',
        'Buffer.md',
        'BufferMemoryRequirements.md',
        'BufferViewCreate.md',
        'CopyBufferToBuffer.md',
        'CopyBufferToDepthStencil.md',
        'CopyBufferToImage.md',
        'CopyDepthStencilToBuffer.md',
        'CopyImageToBuffer.md',
        'CopyImageToImage.md',
        'CopyMemoryIndirect.md',
        'CopyMultiplaneImageTransferQueue.md',
        'DSColorBitCopy.md',
        'DebugUtils.md',
        'DescriptorPool.md',
        'DeviceDrmProperties.md',
        'DeviceInitialization.md',
        'DriverProperties.md',
        'ExtensionDuplicates.md',
        'ExternalMemory.md',
        'FeatureInfo.md',
        'FillBuffer.md',
        'FormatPropertiesExtendedKHR.md',
        'FrameBoundary.md',
        'GetDeviceProcAddr.md',
        'GetMemoryCommitment.md',
        'Granularity.md',
        'ImageClearing.md',
        'ImageCompressionControl.md',
        'Maintenance3Check.md',
        'Maintenance6Check.md',
        'Maintenance7.md',
        'MemoryRequirementInvariance.md',
        'NullHandle.md',
        'ObjectManagement.md',
        'PerformanceCountersByRegion.md',
        'PhysicalDeviceFormatPropertiesMaint5.md',
        'Pipeline.md',
        'ToolingInfo.md',
        'VersionCheck.md',
    },
    'dgc': {
        'ComputeGetInfo.md',
        'ComputeGetInfoExt.md',
    },
    'dynamic_state': {
        'CB.md',
        'Clear.md',
        'DS.md',
        'LineWidth.md',
    },
    'drm_format_modifiers': {
        'Modifiers.md',
    },
    'draw': {
        'AhbTests.md',
        'DiscardRectanglesTests.md',
        'IndirectInstancedTests.md',
        'IndirectTest.md',
        'MultipleClearsWithinRenderPass.md',
        'NegativeViewportHeightTests.md',
        'NonLineTests.md',
        'ScissorTests.md',
    },
    'fragment_operations': {
        'OcclusionQuery.md',
        'Scissor.md',
    },
    'device_group': {
        'Rendering.md',
    },
    'image_processing': {
        'ApiTests.md',
    },
    'imageless_framebuffer': {
        'Tests.md',
    },
    'rasterization': {
        'DepthBiasControl.md',
    },
    'image': {
        'ConcurrentCopy.md',
        'ExtendedUsageBit.md',
        'SubresourceLayout.md',
        'Transfer.md',
    },
    'info': {
        'ApiFeatureInfo.md',
        'InfoTests.md',
    },
    'memory': {
        'AddressBinding.md',
        'Allocation.md',
        'Binding.md',
        'Decompression.md',
        'DeviceMemoryReport.md',
        'ExternalMemoryAcquireUnmodified.md',
        'Mapping.md',
        'Requirements.md',
    },
    'pipeline': {
        'Binary.md',
        'BlendOperationAdvanced.md',
        'Cache.md',
        'CreationCacheControl.md',
        'CreationFeedback.md',
        'Depth.md',
        'DepthRangeUnrestricted.md',
        'Derivative.md',
        'EarlyDestroy.md',
        'ExecutableProperties.md',
        'ExtendedDynamicState.md',
        'InputAssembly.md',
        'Library.md',
        'LogicOp.md',
        'MatchedAttachments.md',
        'Multisample.md',
        'MultisampleResolveRenderArea.md',
        'NoQueues.md',
        'RenderToImage.md',
        'Stencil.md',
        'Timestamp.md',
    },
    'protected_memory': {
        'AttachmentClear.md',
        'AttachmentLoad.md',
        'BlitImage.md',
        'ClearColorImage.md',
        'CopyBufferToImage.md',
        'CopyImage.md',
        'CopyImageToBuffer.md',
        'FillUpdateCopyBuffer.md',
    },
    'query_pool': {
        'Concurrent.md',
        'Maintenance7.md',
        'Performance.md',
    },
    'ray_tracing_pipeline': {
        'Limits.md',
    },
    'renderpasses': {
        'ClearSomeAttachments.md',
        'Dithering.md',
        'DynamicRendering.md',
        'DynamicRenderingMultiviewClear.md',
        'MultipleSubpassesMultipleCommandBuffers.md',
        'SparseRenderTarget.md',
        'SubpassMergeFeedback.md',
        'UnusedAttachment.md',
        'UnusedClearAttachment.md',
    },
    'shader_object': {
        'ApiTests.md',
        'BinaryTests.md',
        'BindingTests.md',
        'CreateTests.md',
        'LinkTests.md',
        'PipelineInteractionTests.md',
    },
    'sparse_resources': {
        'ImageAlignedMipSize.md',
        'ImageBlockShapes.md',
        'ImageRebind.md',
        'ImageSparseBinding.md',
        'MipmapSparseResidency.md',
        'QueueBindSparseTests.md',
        'TransferQueueTests.md',
    },
    'synchronization': {
        'BasicEvent.md',
        'BasicFence.md',
        'BasicSemaphore.md',
    },
    'tessellation': {
        'Limits.md',
    },
    'ycbcr': {
        'Copy.md',
        'ImageOffset.md',
    },
    'wsi': {
        'AcquireDrmDisplayTests.md',
        'DisplayTests.md',
        'DisplayTimingTests.md',
        'FullScreenExclusiveTests.md',
        'Maintenance1Tests.md',
        'PresentIdWaitTests.md',
        'PresentTimingTests.md',
        'SharedPresentableImageTests.md',
        'SurfaceTests.md',
        'SwapchainTests.md',
    },
    'video': {
        'Capabilities.md',
        'ProfilesValidation.md',
        'Decode.md',
        'Encode.md',
        'EncodeAV1.md',
        'Synchronization.md',
    },
}
